name: vuka265
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+13

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  algolia: 1.1.1
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  carousel_slider: 5.0.0
  cloud_firestore: 5.6.9
  cloud_firestore_platform_interface: 6.6.9
  cloud_firestore_web: 4.4.9
  cloud_functions: ^5.1.3
  csslib: 1.0.2
  device_info_plus: ^11.3.0
  device_info_plus_platform_interface: ^7.0.0
  dropdown_button2: 2.3.9
  easy_debounce: 2.0.1
  equatable: 2.0.7
  file_picker: 10.1.9
  firebase_analytics: 11.5.0
  firebase_analytics_platform_interface: 4.4.0
  firebase_analytics_web: 0.5.10+13
  firebase_auth: 5.6.0
  firebase_auth_platform_interface: 7.7.0
  firebase_auth_web: 5.15.0
  firebase_core: ^3.14.0
  firebase_core_platform_interface: 5.4.0
  firebase_core_web: 2.23.0
  firebase_crashlytics: 4.3.7
  firebase_crashlytics_platform_interface: 3.8.7
  firebase_performance: 0.10.1+7
  firebase_performance_platform_interface: 0.1.5+7
  firebase_performance_web: 0.1.7+13
  firebase_storage: 12.4.7
  firebase_storage_platform_interface: 5.2.7
  firebase_storage_web: 3.10.14
  firebase_messaging: ^15.2.7
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  flutter_card_swiper: 6.0.0
  flutter_facebook_auth: 7.1.2
  flutter_facebook_auth_platform_interface: 6.1.2
  flutter_facebook_auth_web: 6.1.2
  flutter_plugin_android_lifecycle: 2.0.28
  flutter_spinkit: 5.2.0
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  geolocator: 13.0.4
  # Use platform implementations via federated plugins; let solver pick compatible geolocator_android 4.x
  geolocator_apple: 2.3.13
  geolocator_platform_interface: 4.2.6
  geolocator_web: 4.1.3
  geolocator_windows: 0.2.5
  go_router: 12.1.3
  google_fonts: ^4.0.0
  google_mobile_ads: 6.0.0
  google_sign_in: 6.3.0
  google_sign_in_android: 6.2.1
  google_sign_in_ios: 5.9.0
  google_sign_in_platform_interface: 2.5.0
  google_sign_in_web: 0.12.4+4
  html: 0.15.6
  image_picker: 1.1.2
  image_picker_android: ^0.8.11
  image_picker_for_web: 3.0.6
  image_picker_ios: 0.8.12+2
  image_picker_linux: 0.2.1+2
  image_picker_macos: 0.2.1+2
  image_picker_platform_interface: 2.10.1
  image_picker_windows: 0.2.1+1
  json_path: 0.7.2
  lottie: 3.1.2
  mask_text_input_formatter: 2.9.0
  mime_type: 1.0.0
  http: ^1.2.2
  package_info_plus: 8.0.2
  package_info_plus_platform_interface: 3.0.1
  page_transition: 2.1.0
  path_provider: 2.1.4
  path_provider_android: 2.2.10
  path_provider_foundation: 2.4.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  percent_indicator: 4.2.2
  permission_handler: 12.0.0+1
  permission_handler_android: ^13.0.0
  permission_handler_apple: 9.4.7
  permission_handler_html: 0.1.3+5
  permission_handler_platform_interface: 4.3.0
  permission_handler_windows: 0.2.1
  plugin_platform_interface: 2.1.8
  provider: 6.1.5
  rxdart: 0.27.7
  shared_preferences: 2.5.3
  shared_preferences_android: 2.4.10
  shared_preferences_foundation: 2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.3
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: 7.0.1
  sign_in_with_apple_platform_interface: 2.0.0
  sign_in_with_apple_web: 3.0.0
  smooth_page_indicator: 1.1.0
  sqflite: 2.3.3+1
  sqflite_common: 2.5.4+3
  stream_transform: 2.1.0
  timeago: 3.7.1
  tutorial_coach_mark: 1.2.11
  universal_io: 2.2.2
  url_launcher: 6.3.1
  url_launcher_android: 6.3.16
  url_launcher_ios: 6.3.3
  url_launcher_linux: 3.2.1
  url_launcher_macos: 3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.4.1
  url_launcher_windows: 3.1.4
  video_player: ^2.9.2
  video_player_android: ^2.7.7
  video_player_avfoundation: ^2.6.1
  video_player_platform_interface: ^6.2.2
  video_player_web: ^2.3.2
  agora_rtc_engine: ^6.0.0
  emoji_picker_flutter: ^1.6.4
  # Audio recording: use stable version 4.4.4 that works reliably across all platforms
  # Version 5.x has federated plugin architecture issues causing iOS IPA build failures
  record: 4.4.4
  audioplayers: ^6.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  uuid: ^4.4.2
  http: ^1.2.2
  package_info_plus: 8.0.2
  package_info_plus_platform_interface: 3.0.1
  video_player_web: ^2.3.2
  image: 4.2.0
  # Workaround App Store build failure: transitive google_api_headers plugin metadata
  # Pin to a stable, pure-Dart version without federated plugin entries.
  google_api_headers: ^4.2.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

    - assets/environment_values/
  fonts:
    - family: 'Onest'
      fonts:
        - asset: assets/fonts/Onest-Thin.ttf
          weight: 100
        - asset: assets/fonts/Onest-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Onest-Light.ttf
          weight: 300
        - asset: assets/fonts/Onest-Regular.ttf
        - asset: assets/fonts/Onest-Medium.ttf
          weight: 500
        - asset: assets/fonts/Onest-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Onest-Bold.ttf
          weight: 700
        - asset: assets/fonts/Onest-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Onest-Black.ttf
          weight: 900

    - family: BootstrapFlutterMartCom
      fonts:
        - asset: assets/fonts/Bootstrap_FlutterMart_com.ttf
    - family: CooliconsFlutterMartCom
      fonts:
        - asset: assets/fonts/Coolicons_FlutterMart_com.ttf
    - family: HeroiconsFlutterMartCom
      fonts:
        - asset: assets/fonts/Heroicons_FlutterMart_com.ttf
    - family: Heroicons2FlutterMartCom
      fonts:
        - asset: assets/fonts/Heroicons2_FlutterMart_com.ttf
    - family: DatingerIcon
      fonts:
        - asset: assets/fonts/Datinger_icon.ttf
    - family: UntitledUi
      fonts:
        - asset: assets/fonts/UntitledUi.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

